{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fast Error Budget Burn Critical Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "status_class_5xx:apiserver_request_total:ratio_rate_5m{job=\"apiserver\"}",
     "legendFormat": "short window"
    },
    { "expr": "(14.4/100*(1-(99.99/100)))", "legendFormat": "fast_burn" },
    {
     "expr": "status_class_5xx:apiserver_request_total:ratio_rate_1h{job=\"apiserver\",}",
     "legendFormat": "long window"
    }
   ]
  },
  {
   "title": "Slow Error Budget Burn Critical Alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(6/100*(1-(99.99/100)))", "legendFormat": "slow_burn" },
    {
     "expr": "status_class_5xx:apiserver_request_total:ratio_rate_6h{job=\"apiserver\",}",
     "legendFormat": "short window"
    },
    {
     "expr": "status_class_5xx:apiserver_request_total:ratio_rate_30m{job=\"apiserver\",}",
     "legendFormat": "long window"
    }
   ]
  },
  {
   "title": "Slow Error Budget Burn Warning Alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(1/100*(1-(99.99/100)))", "legendFormat": "slow burn" },
    {
     "expr": "status_class_5xx:apiserver_request_total:ratio_rate_3d{job=\"apiserver\",}",
     "legendFormat": "long window"
    },
    {
     "expr": "status_class_5xx:apiserver_request_total:ratio_rate_6h{job=\"apiserver\",}",
     "legendFormat": "short window"
    }
   ]
  },
  {
   "title": "Fast Error Budget Burn Warning Alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(3/100*(1-(99.99/100)))", "legendFormat": "fast burn" },
    {
     "expr": "status_class_5xx:apiserver_request_total:ratio_rate_1d{job=\"apiserver\",}",
     "legendFormat": "long window"
    },
    {
     "expr": "status_class_5xx:apiserver_request_total:ratio_rate_2h{job=\"apiserver\",}",
     "legendFormat": "short window"
    }
   ]
  },
  {
   "title": "Remaining Error Budget",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((1-(99.99/100))-status_class_5xx:apiserver_request_total:ratio_rate_3d{job=\"apiserver\",})/(1-(99.99/100))",
     "legendFormat": "error budget"
    }
   ]
  }
 ]
}